### ISSUE TITLE
error running jansenrit.py (jrc.compile) on MacOS

### ISSUE THREAD

**Issue by julama** [pyrates-neuroscience/PyRates#29] opened 2021-12-05 19:35 UTC
Hi, I have an issue when running the example jansenrit.py. 
I'm using a conda environment and MacOS. Any ideas how to resolve the error?

```
Traceback (most recent call last):
  File "/Users/julian/Simulations/pyrates/jansenrit.py", line 113, in <module>
    jrc_compiled = jrc.compile(backend='numpy', step_size=1e-4, solver='scipy')
  File "/Users/julian/opt/miniconda3/envs/ADL/lib/python3.7/site-packages/pyrates/ir/circuit.py", line 1491, in compile
    squeeze=squeeze_vars)
  File "/Users/julian/opt/miniconda3/envs/ADL/lib/python3.7/site-packages/pyrates/backend/parser.py", line 800, in parse_equations
    instantaneous=instantaneous, **kwargs.copy())
TypeError: Can't instantiate abstract class ExpressionParser with abstract methods _generateDefaultName
```

Thank you

**Comment by Richert** [comment] 2021-12-06 10:19
Dear Julian,

thank you for your interest in PyRates! I suspect that this error is caused by a version conflict with `pyparsing`, since the `ExpressionParser` class inherits from `pyparsing.ParserElement`. 
Can you tell me which version you have installed in your Python environment? Personally, I am running PyRates with `pyparsing == 2.4.6` without running into that issue. If that solves the problem, let me know so I can update our dependencies accordingly or make the `ExpressionParser` compatible with the latest `pyparsing` version.

Just as a heads-up: I am currently working on a larger upgrade to PyRates which will replace the current mathematical expression parsing with expression parsing based on `sympy` besides other improvements. I expect to merge these changes into the master branch in January and upgrade the PyRates pypi version soon after.

Best,
Richard

**Comment by julama** [comment] 2021-12-06 11:33
Dear Richard,

I downgraded `pyparsing==3.0.6` to `pyparsing==2.4.6` which resolved the issue. 

Thank you for the quick help!

**Comment by Richert** [comment] 2021-12-06 16:38
Dear Julian,

glad I could help! I will close this issue then.

**Closed by Richert** 2021-12-06 16:38 UTC
